#!/usr/bin/env bash
set -eo pipefail
root=$(cd "$(dirname "$0")/../.." && pwd)
source /opt/ros/jazzy/setup.bash
commit=7aeeddc449edf8d62b594f9e36a81da53e7796f9
vendor="$root/.vendor/franka_description"
if [[ ! -d "$vendor/.git" ]]; then git clone --filter=blob:none --no-checkout https://github.com/frankarobotics/franka_description.git "$vendor"; fi
git -C "$vendor" fetch --depth 1 origin "$commit"
git -C "$vendor" checkout --detach "$commit"
prefix="$root/.vendor/franka_prefix"
mkdir -p "$prefix/share/ament_index/resource_index/packages" "$root/models/fr3"
touch "$prefix/share/ament_index/resource_index/packages/franka_description"
ln -sfn "$vendor" "$prefix/share/franka_description"
export AMENT_PREFIX_PATH="$prefix:$AMENT_PREFIX_PATH"
cd "$vendor"
python3 scripts/create_urdf.py fr3 --no-ee
python3 scripts/create_urdf.py fr3 --robot-ee franka_hand
# Normalize only the autogenerated comment's source-path; model XML remains unchanged.
python3 "$root/scripts/phase1/normalize_urdf.py" "$vendor/urdfs/fr3.urdf" "$root/models/fr3/fr3_arm.urdf" "$vendor"
python3 "$root/scripts/phase1/normalize_urdf.py" "$vendor/urdfs/fr3_franka_hand.urdf" "$root/models/fr3/fr3_with_hand.urdf" "$vendor"
cp LICENSE NOTICE "$root/models/fr3/"
git rev-parse HEAD > "$root/models/fr3/franka_description.commit"
git archive --format=tar.gz --output="$root/models/fr3/official_source.tar.gz" "$commit" robots/common robots/fr3 end_effectors/common end_effectors/franka_hand scripts/create_urdf.py LICENSE NOTICE package.xml
cd "$root"
if [[ -f models/fr3/urdf.sha256 ]]; then sha256sum -c models/fr3/urdf.sha256; fi
sha256sum models/fr3/*.urdf > models/fr3/urdf.sha256
sha256sum models/fr3/official_source.tar.gz > models/fr3/official_source.sha256
