"""Offline source-generation normalization, never a runtime robot implementation."""
import pathlib
import sys
source, target, vendor = map(pathlib.Path, sys.argv[1:])
vendor=vendor.resolve()
lines=source.read_text().splitlines(keepends=True)
lines=[line.replace(str(vendor),'franka_description') if 'autogenerated by xacro from' in line else line for line in lines]
target.write_text(''.join(lines))
