#!/usr/bin/env python3
import csv,json,hashlib
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
p=Path('/home/codextransfer/predictive_motion');base=p/'results/phase5/development/servo-safe-reference-v3-validation';raw=Path('/mnt/d/CodexTransfer/projects/predictive_motion/phase5/raw/servo-safe-reference-v3-validation/raw.csv');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();row=list(csv.DictReader(raw.open()))[-1]
image=Image.new('RGB',(1280,840),'#101d30');image.paste(Image.open(base/'recorded_v3_final_state.ppm'),(0,88));draw=ImageDraw.Draw(image);font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',28);small=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',19)
draw.text((26,17),'FR3 v3 recorded final state | guard run and shared stop complete',font=font,fill='white');draw.text((26,55),'MuJoCo 3.3.7 · saved measured q/v and accepted target · geometry render only',font=small,fill='#b8cedf');draw.rectangle((0,750,1280,840),fill='#101d30');draw.text((26,766),f'Virtual t={float(row["time_s"]):.3f}s · clearance={float(row["true_clearance_m"])*1000:.2f}mm · contacts={row["contacts"]} · shared stop after hold',font=small,fill='white');draw.text((26,800),'Frozen predictor fails 2/4ms limits. This pose render does not establish expanded model or controller acceptance.',font=small,fill='#b8cedf')
out=base/'phase5_servo_safe_reference_v3_final_state.png';image.save(out);manifest=p/'src/predictive_motion_description/manifests/fr3.sha256'
for line in manifest.read_text().splitlines():
 expected,name=line.split(None,1);assert sha(p/'.vendor/menagerie'/name.strip())==expected
inputs=[raw,base/'recorded_v3_final_state.ppm',p/'experiments/generated/inspection/scene.xml',p/'experiments/generated/inspection/inspection_fr3.xml',p/'tools/phase5_servo_diagnostics/render_servo_recorded_pose.cpp',p/'build-servo-qp-reconstruct-v1/render_servo_recorded_pose',Path(__file__)]
meta={'output_sha256':sha(out),'source_hashes':{str(f):sha(f) for f in inputs},'upstream_asset_manifest_sha256':sha(manifest),'model_length_units':'metres;joint q radians;unchanged model/CAD','camera':{'lookat_m':[.49,-.01,.49],'distance_m':1.5,'azimuth_deg':135,'elevation_deg':-23},'record':{'tick':int(row['tick']),'time_s':float(row['time_s']),'q_post_rad':[float(row['q_post_'+str(j)]) for j in range(7)]},'scope':'Actual recorded end pose, forward geometry only; no new physics/control or predictor/controller acceptance; shared stop follows hold','renderer':'Existing OSMesa/MuJoCo3.3.7','completed_stop':True};(base/'phase5_servo_safe_reference_v3_final_state.json').write_text(json.dumps(meta,indent=2)+'\n');print(sha(out))
