#!/usr/bin/env python3
import datetime,hashlib,json,tarfile
from pathlib import Path
p=Path('/home/codextransfer/predictive_motion');base=p/'results/phase5/development/servo-safe-reference-v3-validation';raw=Path('/mnt/d/CodexTransfer/projects/predictive_motion/phase5/raw/servo-safe-reference-v3-validation');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();freeze=json.loads((base/'frozen.json').read_text());cache=Path('/mnt/d/CodexTransfer/projects/predictive_motion/phase5/identity-cache');closure=[]
for name,h in freeze['files'].items():
 f=cache/h;assert f.exists() and sha(f)==h;closure.append({'original_path':name,'sha256':h,'bytes':f.stat().st_size})
(base/'verified_input_closure.json').write_text(json.dumps({'inputs':len(closure),'missing':[],'verified_on_dell':str(cache),'mac_full_cache_not_verified':True,'files':closure},indent=2)+'\n')
review=p/'reviews/phase_5_servo_safe_reference_v3_20261007.md'
review.write_text('''# v3 prospective curated-reference development run

Fixture return0, shared stop completed; predictor FAIL_EXPANDED_RECORDED_TRACE and original frozen domain FAIL_MODEL_INELIGIBLE. Phase5 remains unaccepted; no main MPC or causal model module integration, no predictor refit or threshold/domain modification. Root independent signed-cone review and explicit approval included in197 prefrozen input identities; all immutable cache bytes verified on Dell. Native OSQP1.0.0, SOLVED-only, original SI1e-7,4000iterations,50ms solver/live observation/stop guards unchanged. Solver stopping1e-12 prospectively selected from independent prior captured-QP precision audit. Command cone rows added to tracking and shared stop; actual candidate(next_w,next_alpha) must have a continuable next history under fixed V=.0625,A=1,J20,dt.004. Rows alone or SI tolerance are not a strict continuation certificate; no blindly clipped commands.

Frozen servo model984ee85d086aeba7da8260a20b21b301e23dfd2c698a6c61ace0ff956bbec1bb before/after. Seed91012 is development reuse with curated previously seen accepted w inputs, no untouched holdout. Reference offsets are not chased; actual accepted target integrates guarded w. Whole physical trace retained including all transitions. Correct cycle roster500warmup/195reference motion/233reference recorded braking/1572hold/1new shared stop. Only428 cycles/1.712s are movement/reference braking. Last tick2500/time10.004; final shared stop follows a long hold already near rest, so not a new moving-state stopping challenge. Stop successful for this trace only.

2002 actual tracking/stop solve attempts are native raw1/API SOLVED. Every actual A/l/u and native/API statuses, candidate size/coordinates, max violation/row, age and timing directly logged. Independent actual-row validation maximum1.6399326341343112e-10≤1e-7. All2001 nonwarmup accepted histories pass continuation post-check; command age max.017855068s<.05. Full-cycle4ms deadline misses2001, maxwall.019170534s: no online250Hz claim. Physical maxv.0299222377166rad/s, minimum measured clearance.0155670314094m; final accepted w0, physical speed4.900134322334646e-12. H/g were not directly exported per accepted solve: exact matrices are determined by frozen tracking/stopping source plus w_reference inputs. First-rejection full H/g snapshot mechanism remained inactive because no rejection occurred. This distinction is retained, not disguised as actual per-solve H/g capture.

Predictor same2/4/40/800ms criteria:2ms maximum v error2.696411576707568e-4 exceeds1e-4;4ms q1.1625050619912258e-6 exceeds1e-6 and v3.11611373310611e-4 exceeds1e-4. Worst2/4 q start tick730/joint3 in reference braking.40ms q1.621974296295292e-5,v5.295642594978466e-4 pass;800ms q3.822768857464354e-5,v4.554748255206683e-4 pass. All windows are included without deleting old-domain violations or braking.2001/2001/1992/1802 overlapping windows are not independent trials; hold-only counts1572/1572/1563/1373;428windows in each contain motion/reference braking. Original model has3827active measured rows outside its domain. Prospectively declared diagnostic box has no measured or800ms-predicted violations, but short-step error failures prohibit enlarged eligibility. Original model metadata remains unchanged. No thresholds relaxed to force pass.

Retained setup failures: requesting the new target before CMake regeneration gave no-rule/exit2; regeneration without existing ROS setup caused ament_package import failure/exit1. Sourcing existing /opt/ros/jazzy/setup.bash repaired environment without installations or relaxed flags. Final binary built with inherited unused-variable warnings explicitly unclean; no mathematical guard change.

Inspected plot presents all actual accepted/physical velocity trace and original error ratios; hold shaded explicitly. New actual final-pose render reuses frozen MuJoCo3.3.7/OSMesa tool and upstream FR3 assets verified from manifest, q/v/accepted target from raw; mj_forward only, no mj_step or new commanded trajectory. Units metres/radians unchanged; camera/data/source/image hashes recorded. No new CAD geometry. Neither render nor diagnostic figure establishes controller/model acceptance. Root owns small source/figures/showcase/private-Git backup; raw archive copies identify separately verified storage.
''')
images=[base/'phase5_servo_safe_reference_v3.png',base/'phase5_servo_safe_reference_v3_final_state.png'];(base/'visual_inspection.json').write_text(json.dumps({'images':{f.name:sha(f) for f in images},'status':'PASS_PRESENTATION_LAYOUT','inspected_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'findings':'Actual command/physical trace, shaded hold and 2/4ms failures legible; actual final pose and caveat uncut, calibrated metre/radian model, original upstream assets checked.'},indent=2)+'\n')
sources=['tools/phase5_servo_reference/CMakeLists.txt','tools/phase5_servo_reference/servo_safe_reference_cone_fixture.cpp','scripts/phase5/prepare_servo_safe_reference_v3.py','scripts/phase5/prepare_servo_safe_reference_v3_runner.py','scripts/phase5/finalize_servo_safe_reference_v3_freeze.py','scripts/phase5/run_servo_safe_reference_v3.py','scripts/phase5/validate_servo_safe_reference_v3.py','scripts/phase5/audit_servo_safe_reference_v3.py','scripts/phase5/annotate_servo_safe_reference_v3_render.py','scripts/phase5/publish_servo_safe_reference_v3.py','config/phase5_development/servo_validation_safe_reference_v3.yaml','config/phase5_development/servo_validation_safe_reference_v3.authorization.json',str(review.relative_to(p))];items={'project/'+s:p/s for s in sources}
for name,h in freeze['files'].items():
 if '/phase5_servo_reference/' in name or '/build-servo-safe-reference-v1/' in name or 'servo_safe_reference_v3' in name or 'servo_validation_safe_reference_v3' in name or '/phase5_command_cone/' in name or 'signed_command_cone_math_audit' in name:items['frozen-input-cache/'+h]=cache/h
for f in base.rglob('*'):
 if f.is_file():items['project/'+str(f.relative_to(p))]=f
for f in raw.rglob('*'):
 if f.is_file():items['raw/'+str(f.relative_to(raw))]=f
for f in [p/'results/phase5/development/servo-model-soft-friction-v2-frozen/model.json',p/'results/phase5/development/servo-safe-reference-v1/accepted_target_increments.csv',p/'results/phase5/development/servo-safe-reference-v1/reference_identity.json',p/'tools/phase5_command_cone/signed_velocity_cone.hpp',p/'tools/phase5_servo_diagnostics/render_servo_recorded_pose.cpp',p/'build-servo-qp-reconstruct-v1/render_servo_recorded_pose']:items['project/'+str(f.relative_to(p))]=f
manifest={name:{'sha256':sha(f),'bytes':f.stat().st_size} for name,f in items.items()};(base/'CHECKPOINT_FILE_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n')
small={s:manifest['project/'+s] for s in sources}
for name in ['model-audit/validation_report.json','actual_guard_phase_audit.json','phase5_servo_safe_reference_v3.png','phase5_servo_safe_reference_v3.json','phase5_servo_safe_reference_v3_final_state.png','phase5_servo_safe_reference_v3_final_state.json','visual_inspection.json']:
 f=base/name;small[str(f.relative_to(p))]={'sha256':sha(f),'bytes':f.stat().st_size}
(base/'BACKUP_SOURCE_MANIFEST.json').write_text(json.dumps(small,indent=2)+'\n')
for name in ['CHECKPOINT_FILE_MANIFEST.json','BACKUP_SOURCE_MANIFEST.json']:items['project/'+str((base/name).relative_to(p))]=base/name
dest=Path('/mnt/d/CodexTransfer/projects/predictive_motion/checkpoints/servo-safe-reference-v3-20261007');dest.mkdir(exist_ok=False);part=dest/'servo-safe-reference-v3.tar.gz.part'
with tarfile.open(part,'w:gz') as t:
 for name,f in sorted(items.items()):t.add(f,arcname=name,recursive=False)
archive=dest/'servo-safe-reference-v3.tar.gz';part.rename(archive)
with tarfile.open(archive) as t:
 assert len(t.getmembers())==len(items)
 for m in t.getmembers():assert m.isfile() and m.name in items and hashlib.sha256(t.extractfile(m).read()).hexdigest()==sha(items[m.name])
ready={'archive':str(archive),'sha256':sha(archive),'bytes':archive.stat().st_size,'members':len(items),'archive_members_verified':True,'dell_cached_inputs_verified':len(closure),'mac_copy_verified':False,'source_manifest':str(base/'BACKUP_SOURCE_MANIFEST.json'),'source_manifest_sha256':sha(base/'BACKUP_SOURCE_MANIFEST.json'),'scope':'Successful curated guard/hold-end stop trace but short-step prediction FAIL; old domain ineligible; no controller/online250Hz/Phase5 acceptance'}
(dest/'READY.json.part').write_text(json.dumps(ready,indent=2)+'\n');(dest/'READY.json.part').rename(dest/'READY.json');print(json.dumps(ready,indent=2))
