#!/usr/bin/env python3
"""Immutable command/progress extension Jacobian evidence, no admissibility claim."""
import json,hashlib,tarfile
from pathlib import Path
ROOT=Path('/home/codextransfer/predictive_motion');BASE=ROOT/'results/phase5/development/public-coupled-augmented-extension-cpp-v1'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def save(p,x):Path(p).write_text(json.dumps(x,indent=2,allow_nan=False)+'\n')
assert (BASE/'visual_inspection.json').is_file(),'require final visual record before archive snapshot'
freeze_path=BASE/'frozen_before_predictions.json';freeze=json.loads(freeze_path.read_text());report=json.loads((BASE/'parity-attempt1/report.json').read_text());assert report['status']=='PASS_SELECTED_COMMAND_PROGRESS_EXTENSION_JACOBIANS_ONLY' and report['freeze_sha256']==sha(freeze_path)
for r in freeze['files']:assert sha(r['path'])==r['sha256'] and sha(r['immutable_copy'])==r['sha256']
positive=[x for x in report['records'] if x['extension_jacobian_success']];unsupported=[x for x in report['records'] if x['value_success'] and not x['extension_jacobian_success']];failed=[x for x in report['records'] if not x['value_success']]
stats=[dict(epsilon=e,max_absolute=max(x['epsilons'][i]['max_absolute'] for x in positive),max_gate_ratio=max(x['epsilons'][i]['max_gate_ratio'] for x in positive)) for i,e in enumerate(report['epsilons'])]
review=ROOT/'reviews/phase_5_public_coupled_augmented_extension_20261008.md'
review.write_text(f'''# Composite Jacobians induced by command/progress extension

Phase5 remains NOT_ACCEPTED and Phase6 NOT_STARTED. This bounded unit follows the independently remote-verified checkpoint a3a2960f4d1d8f25ece6041f36dcbddeb3b6b59d. It adds a separate namespace, Model, Result and CLI. Original a29 interior sensitivity, 2fa augmented value, e2c physical derivative and fa1 physical value sources/binaries, public constants, seen records and SDK remain unchanged. There is no fitting, new plant, untouched evaluation, horizon/cost/main-controller integration or task/timing acceptance.

The new certificate is COMMAND_PROGRESS_EXTENSION_JACOBIAN_STRICT_PHYSICAL_V1, returned through extension_jacobian_success. It names the derivative of the nonlinear composite map induced by the smooth command/progress polynomial extension. The full physical map remains nonlinear. With h=.004 s, w_next=w+h*alpha and C_next=C+h*w_next; the accepted C_next is held for both original 2 ms physical steps. Within a cell, s(t)=s0+t*r0+.5*t²*b and r(t)=r0+t*b at each half/full time. Nominal outputs remain the exact original 2fa rollout, including iterative cycle progress and cell-origin half references. The wrapper never resets nominal state from its affine model or rational oracle.

Nominal w in[-.0625,.0625], alpha in[-1,1], s in[0,1] and r in[0,.2] are accepted inclusively. No actual history/progress is projected or shifted to epsilon. Initial/generated C must remain more than 1e-8 rad inside its public bounds; q/v and every physical step retain all original e2c strict clamp/friction, finite, SPD, condition and residual gates. Physical/C thresholds are still unsupported. b remains finite-only; original mesh caps and canonical integer parser rules remain exact.

Policy, cases and every certified prefix map explicitly set certifies_two_sided_admissible_neighborhood=false. That limits the certificate's scope; it does not assert that interior nominal points lack an admissible neighborhood. Origin/endpoint boundary side metadata is diagnostic. J_ext*d is an admissible one-sided derivative only when the direction also keeps the original forward valid at every half/full time. This API supplies no admissible-direction, tangent, continuation, safety, accuracy or main-readiness certificate. Exterior w/alpha/s/r points occur only in tagged mathematical extension probes, never accepted as new-API/2fa nominal commands or histories.

Cycle and cell derivatives retain the previously audited composition. If J1=(P1,Q1) and J2=(P2,Q2) is evaluated at the actual first-half q/v and held C, then P=P2*P1 and Q=P2*Q1+Q2. Physical cycle A blocks are(P,Q,hQ), and B_alpha=h²Q. Command rows have C_C=I, C_w=hI, B_Calpha=h²I, w_w=I and B_walpha=hI. Progress A=[[1,h],[0,1]], B_b=[.5h²,h]. The first half uses J1 and t=.002 while preserving the full 4 ms latch. Held-cell A_new=A_cycle*A_old and B_new=A_cycle*B_old+B_cycle. Each defect is exact original endpoint minus A*matched origin minus B*held input. All matrix products, sums and intermediate defect arithmetic remain finite-guarded.

Original forward failure forbids a full certificate. The result retains the exact original values/errors, last complete cycle or validated initial final state, and all actual completed half traces. Only physically certified actual prefix maps are emitted, with explicit first_uncertified_substep/error. No extended future state replaces a failed forward point, and no stale/zero/fabricated future matrix is returned. A valid closed boundary can now receive an extension derivative where the older central-domain API refused, but an original forward failure or unchanged physical-policy rejection still stops certification. Half maps remain diagnostics rather than ordinary 4 ms initializations.

Root approved the API, policy and exact-oracle contract before predictions. First configure/build succeeded. The initial naming proposal and source are retained in static-proposal1; naming was clarified before predictions to specify command/progress extension and the nonlinear physical map. Empty metadata/semantic preflight passed the frozen native helper and new schema. Freeze {sha(freeze_path)} contains {len(freeze['files'])} verified live/immutable identities, including all prior 2611 identities, the new source/contract/harness, nominal and extension cases, exact rational physical target inputs and exterior labels. No new numerical forecast preceded the complete freeze.

The producer predeclared 28 nominal cases: 17 prospective supported fixtures, three valid physical/C thresholds, six invalid dimension/parser/outside inputs and two future failures. Supported fixtures include declared 0/0 progress starts, terminal 1/0, both w/alpha bounds, initial/generated progress bounds, inward w continuation, nonuniform[1,3,2,4] cells, a previously seen tick690 accepted command history with explicitly virtual 0/0 progress, and a copied interior reference. All nominal forward results, errors and partial traces equal original 2fa exactly. Interior numerical maps equal original a29 bit-for-bit. Virtual progress is not recorded task progress; the seen seed is not a new or untouched evaluation.

The producer's first numerical attempt passed its own declared gates without any source/input/parameter/epsilon/policy repair: {len(positive)} extension-certified, {len(unsupported)} value-only and {len(failed)} forward-failed cases. Original e2c supplies {report['independent_nominal_physical_derivatives']} independent nominal J1/J2 comparisons. Rational command/progress coefficients, h²Q/hQ, every-half semiimplicit q sensitivity and matched defects pass the fixed 2e-13 structural gates.

The independent root audit did NOT pass its original full same-branch two-epsilon gate. Saved output diagnosis identifies exactly two changed probes in root_boundary_initial_w_plusV: epsilon1e-6, initial q[1]+epsilon and C[1]-epsilon, first half, friction joint index1. Nominal force is -1.137 N m, lower branch -1, with original-H active gradient +.0032122965091645472. The two probes have free branch0 and forces -1.1353588526545577 /-1.1353428923460955 N m; their free force margins are about .00164/.00166 N m. All other physical clamp signatures remain unchanged, and each point individually passed the strict physical checks. Root reported no branch changes at epsilon3e-7, but that smaller step is not selected to turn the failed two-step gate into a pass.

This counterexample shows that the operational pointwise strict margins do not guarantee the fixed finite probe radius. It does not by itself establish that the analytic derivative at the nominal point is wrong. The failed verification prerequisite remains failed, all original root cases/probes are retained, and there is no full root/unit acceptance claim. The unchanged diagnosis is copied as visual input with its hash; complete root raw evidence, original failed checker and separately predeclared closed-direction controls are retained by the independent backup owner. Root completed a separate saved-output review: PARTIAL_SELECTED_EXTENSION_VALIDATION_WITH_RETAINED_FD_BRANCH_FAILURE. Five of six original cases pass all requested columns at both fixed epsilons, including start0/0, terminal, alpha1, generatedwV and the62-column nonuniform start. The initialwV fixture at1e-6 has maximum derivative discrepancy .9200175809649709, maximum normalized gate ratio36102.10331702078 and56 failed entry comparisons. Its3e-7 ratio .00616081665 is reported separately; the original two-epsilon gate stays failed. Twelve originally predeclared closed-direction controls were completed, with selected plus directions valid at all timestamps and their minus counterparts rejected; this gives no general execution/safety certificate. Two original e2c nominal half calls independently match the failed-case J1/J2 chain, validating nominal composition rather than finite radius. An intermediate saved-review checker incorrectly expected5 future-r halves; original2fa prechecks the complete next-cycle state before physics, so4 retained halves/2cycles are correct. Failed reviewer source/output and corrected expectation are preserved, with no model/input/epsilon/FD-gate change. Any supplementary read-only assessment preserves the original counterexample and decision.

The producer oracle uses {report['extension_oracle_cases']} original fa1 physical self-rollouts over precomputed rational command/progress targets: one nominal and all 30 state plus eight common held-input directions, both signs, both fixed epsilon1e-6/3e-7. Multi-cell input perturbations are shared across cells; root independently tests distinct cell inputs. Exterior nonphysical nodes are explicitly mathematical-only. The reconstructed targets/labels must equal the pre-frozen inputs before calls. {report['exterior_nonphysical_case_count']} oracle cases have exterior nonphysical nodes. Neither old 2fa nor the new API is called on these exterior FD nominal inputs.

Every half, cycle and cell endpoint is compared using |error|<=5e-7+5e-6|analytic| separately at each epsilon. Rational nominal-oracle roundoff tolerances are q1e-12 rad, v1e-11 rad/s and command/progress2e-13; original output is never replaced. {report['original_physical_diagnostics']} original fa1 single-step diagnostics require exact self-rollout q/v parity, unchanged strict C/q support, same nested clamp/friction branches for the producer's probes and finite positive condition<=1e12 M,H,Hff when free,K with full implicit D. Selected producer maxima follow; mixed derivative units and dimensionless normalized gate ratios are preserved:
{json.dumps(stats,indent=2)}

One actual-output schema control passed; {len(report['synthetic_output_gates']['negative_controls'])} altered-output controls were rejected. These check typed flags, named extension certificates, no admissibility claims, exact boundary metadata, complete ordered rosters, matrix/defect dimensions and finiteness, retained prefixes and absence of fabricated unsupported matrices. Synthetic mutations are schema controls, not native failures. Historical failures remain in their existing immutable archives.

Three figures show actual declared-start A/B, the producer's 17-case gates and the independent failed-branch counterexample. They include explicit units, source/input/native/freeze hashes, visual inspection and development-only scope. Initial visual source/pair/provenance/logs are retained in visual-attempt1; legend placement, declared-start wording and root-failure disclosure were improved without numerical changes. The initial counterexample plot with crowded gradient labels is retained in visual-attempt2-failure, then repaired for readability. These figures establish no arm task ranking or accepted performance. No new complete successful Phase5 task trajectory exists for a task-success video; accepted Phase4 CAD and curated task clips remain intact.

The publisher requires the completed visual-inspection record before taking its snapshot. Small source/configuration/QA/review/figures/checkpoint records are imported by the Mac backup owner, while large original inputs, SDK dependencies, raw oracle traces and retained failures remain in verified regular-member SHA/READY archives on Dell and Mac. This is a reproducible development checkpoint with an independent failed gate, not Phase5 acceptance. No further main/plant/next unit begins until failure evidence and the private remote checkpoint are verified and a narrow dispatch is issued.
''')
items={}
def add(name,p):
 p=Path(p)
 if p.is_dir():
  for f in p.rglob('*'):
   if f.is_file() and '__pycache__' not in f.parts:items[name+'/'+str(f.relative_to(p))]=f
 else:items[name]=p
add('project/tools/phase5_public_coupled_augmented_extension_cpp',ROOT/'tools/phase5_public_coupled_augmented_extension_cpp');add('project/'+str(BASE.relative_to(ROOT)),BASE)
for n in ['CHECKPOINT_FILE_MANIFEST.json','BACKUP_SOURCE_MANIFEST.json']:items.pop('project/'+str((BASE/n).relative_to(ROOT)),None)
sources=['scripts/phase5/verify_public_coupled_augmented_extension.py','scripts/phase5/plot_public_coupled_augmented_extension.py','scripts/phase5/plot_public_coupled_augmented_extension_failure.py','scripts/phase5/publish_public_coupled_augmented_extension.py',str(review.relative_to(ROOT))]+['figures/phase5/phase5_public_coupled_augmented_extension_'+stem+ext for stem in ('matrix','verification','failure') for ext in ('.png','.json')];small={}
for name in sources:add('project/'+name,ROOT/name);small[name]=dict(sha256=sha(ROOT/name),bytes=(ROOT/name).stat().st_size)
for p in list((ROOT/'tools/phase5_public_coupled_augmented_extension_cpp').glob('*'))+[freeze_path,BASE/'parity-attempt1/report.json',BASE/'inputs/declared_scope.json',BASE/'contract_before_predictions.json',BASE/'independent_root_diagnosis/BRANCH_GATE_FAILURE_DIAGNOSIS.json',BASE/'visual_inspection.json']:
 if p.is_file():small[str(p.relative_to(ROOT))]=dict(sha256=sha(p),bytes=p.stat().st_size)
for r in freeze['files']:add('immutable_dependencies/'+r['sha256'],r['immutable_copy'])
save(BASE/'CHECKPOINT_FILE_MANIFEST.json',{name:dict(sha256=sha(p),bytes=p.stat().st_size) for name,p in items.items()});save(BASE/'BACKUP_SOURCE_MANIFEST.json',small)
for n in ['CHECKPOINT_FILE_MANIFEST.json','BACKUP_SOURCE_MANIFEST.json']:add('project/'+str((BASE/n).relative_to(ROOT)),BASE/n)
dest=Path('/mnt/d/CodexTransfer/projects/predictive_motion/checkpoints/public-coupled-augmented-extension-cpp-v1-20261008');dest.mkdir(exist_ok=False);part=dest/'public-coupled-augmented-extension-cpp-v1.tar.gz.part'
with tarfile.open(part,'w:gz',dereference=True) as tar:
 for name,p in sorted(items.items()):tar.add(p,arcname=name,recursive=False)
archive=dest/'public-coupled-augmented-extension-cpp-v1.tar.gz';part.rename(archive)
with tarfile.open(archive,'r|gz') as tar:
 count=0
 for m in tar:
  assert m.isfile() and not m.name.startswith('/') and '..' not in Path(m.name).parts and m.name in items
  blob=tar.extractfile(m).read();assert len(blob)==items[m.name].stat().st_size and hashlib.sha256(blob).hexdigest()==sha(items[m.name]);count+=1
assert count==len(items)
for r in freeze['files']:assert sha(r['path'])==r['sha256']
ready=dict(archive=str(archive),sha256=sha(archive),bytes=archive.stat().st_size,regular_members=len(items),archive_payloads_verified=True,frozen_manifest_sha256=sha(freeze_path),source_manifest_sha256=sha(BASE/'BACKUP_SOURCE_MANIFEST.json'),gate=report['status'],independent_root_gate='FAIL_DECLARED_SAME_BRANCH_FD_GATE_RETAINED',all_failures_retained=True,Mac_copy_verified=False,phase5='NOT_ACCEPTED',phase6='NOT_STARTED',scope='Selected nonlinear composite Jacobians induced by command/progress polynomial extension; closednominalforward unchanged; exteriormathematicalprobes only; no admissibility/safety/main/plant/task/timing acceptance.')
save(dest/'READY.json.part',ready);(dest/'READY.json.part').rename(dest/'READY.json');print(json.dumps(ready,indent=2),flush=True)
