#include <mujoco/mujoco.h>
#include <iomanip>
#include <iostream>
template<class T>void values(const char* name,const T* p,int n){std::cout<<'"'<<name<<"\":[";for(int i=0;i<n;++i){if(i)std::cout<<',';std::cout<<+p[i];}std::cout<<"],";}
int main(int argc,char** argv){if(argc!=2)return 2;char error[2048]{};mjModel* m=mj_loadXML(argv[1],nullptr,error,sizeof(error));if(!m){std::cerr<<error;return 3;}
 std::cout<<std::setprecision(17)<<"{\"nv\":"<<m->nv<<",\"nq\":"<<m->nq<<",\"nu\":"<<m->nu<<",\"neq\":"<<m->neq<<",\"integrator\":"<<m->opt.integrator<<",\"disableflags\":"<<m->opt.disableflags<<",\"actuator_disablegroups\":"<<m->opt.disableactuator<<",\"timestep\":"<<m->opt.timestep<<",\"density\":"<<m->opt.density<<",\"viscosity\":"<<m->opt.viscosity<<',';
 values("gravity",m->opt.gravity,3);values("wind",m->opt.wind,3);values("armature",m->dof_armature,m->nv);values("invweight0",m->dof_invweight0,m->nv);values("passive_damping",m->dof_damping,m->nv);values("friction_bounds",m->dof_frictionloss,m->nv);values("solref",m->dof_solref,m->nv*mjNREF);values("solimp",m->dof_solimp,m->nv*mjNIMP);values("joint_stiffness",m->jnt_stiffness,m->njnt);values("joint_range",m->jnt_range,2*m->njnt);values("joint_limited",m->jnt_limited,m->njnt);values("joint_actuator_force_range",m->jnt_actfrcrange,2*m->njnt);values("joint_actuator_force_limited",m->jnt_actfrclimited,m->njnt);
 values("gainprm",m->actuator_gainprm,m->nu*mjNGAIN);values("biasprm",m->actuator_biasprm,m->nu*mjNBIAS);values("gear",m->actuator_gear,6*m->nu);values("control_range",m->actuator_ctrlrange,2*m->nu);values("control_limited",m->actuator_ctrllimited,m->nu);values("actuator_force_range",m->actuator_forcerange,2*m->nu);values("actuator_force_limited",m->actuator_forcelimited,m->nu);values("actuator_dyntype",m->actuator_dyntype,m->nu);values("actuator_gaintype",m->actuator_gaintype,m->nu);values("actuator_biastype",m->actuator_biastype,m->nu);values("actuator_trntype",m->actuator_trntype,m->nu);values("actuator_trnid",m->actuator_trnid,2*m->nu);values("body_gravity_compensation",m->body_gravcomp,m->nbody);
 std::cout<<"\"joint_names\":[";for(int i=0;i<m->njnt;++i){if(i)std::cout<<',';std::cout<<'"'<<mj_id2name(m,mjOBJ_JOINT,i)<<'"';}std::cout<<"],\"version\":\""<<mj_versionString()<<"\",\"minimum_value\":"<<mjMINVAL<<'}';mj_deleteModel(m);return 0;
}
